---
title: "Session 4: Data Import"
output:   
  github_document:
  # or pdf_document or work_document
---

```{r, echo = FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

## Data Import: CSVs

Let's import data using the 'readr' package

```{r}
litters_df <- read_csv('data/FAS_litters.csv')
litters_df <- janitor::clean_names(litters_df)
```


Look at table
```{r}
head(litters_df)
tail(litters_df)
skimr::skim(litters_df)
```


'read_csv' options..
```{r}
read_csv('data/FAS_litters.csv', na = c("", "NA", 999, 88), skip = 2)
?read_csv
# can also set variable type
```

## Other file formats

We need to read in an excel spreadsheet...
```{r}
mlb_df <- read_excel('data/mlb11.xlsx')
```

```{r, eval = FALSE}
view(mlb_df)
```

```{r}
lotr_words_df <-
  read_excel(
    'data/LotR_Words.xlsx',
    range = "B3:D6"
  )
```

## Still more formats ...

Read in SAS dataset
```{r}
pulse_df <- read_sas('data/public_pulse_data.sas7bdat')
```


## Data Export

```{r}
write_csv(lotr_words_df, file = 'data/lotr_words_df.csv')
```

## Why not base r???
```{r}
dont_do_this_df <- read.csv('data/FAS_litters.csv')
```
read.csv saves as data.frame, forces format but not able to change
ALWAYS use read_csv




